import type { Locale } from '../language/i18n';
import type { SidebarArticle } from '../sidebar';
import type { BatchSource } from '../services/batchSettings';

export type ReaderViewLabels = {
  untitled: string;
  unknown: string;
  authors: string;
  abstract: string;
  publishedAt: string;
  source: string;
  fetchedAt: string;
  close: string;
  emptyFiltered: string;
  emptyAll: string;
  startDate: string;
  endDate: string;
  journalFilterPlaceholder: string;
  fetchLatestBusy: string;
  fetchLatest: string;
  resetFilter: string;
  showing: string;
  total: string;
  emptyState: string;
  previewUnavailable: string;
  webPreviewTitle: string;
};

export type ReaderViewProps = {
  isSidebarOpen: boolean;
  filteredArticles: SidebarArticle[];
  hasData: boolean;
  locale: Locale;
  filterJournal: string;
  onFilterJournalChange: (value: string) => void;
  batchStartDate: string;
  onBatchStartDateChange: (value: string) => void;
  batchEndDate: string;
  onBatchEndDateChange: (value: string) => void;
  onFetchLatestBatch: () => void;
  onDownloadPdf: (sourceUrl: string, articleTitle?: string) => Promise<void>;
  isBatchLoading: boolean;
  onResetFilters: () => void;
  filteredCount: number;
  totalCount: number;
  browserUrl: string;
  iframeReloadKey: number;
  electronRuntime: boolean;
  previewRuntime: boolean;
  labels: ReaderViewLabels;
};

export type SettingsViewLabels = {
  settingsTitle: string;
  settingsLoading: string;
  settingsLanguage: string;
  languageChinese: string;
  languageEnglish: string;
  settingsLanguageHint: string;
  settingsPageUrl: string;
  settingsPageUrlHint: string;
  pageUrlPlaceholder: string;
  settingsBatchJournalTitle: string;
  batchJournalTitlePlaceholder: string;
  addBatchUrl: string;
  removeBatchUrl: string;
  moveBatchUrlUp: string;
  moveBatchUrlDown: string;
  settingsBatchOptions: string;
  batchCount: string;
  sameDomainOnly: string;
  settingsBatchHint: string;
  defaultPdfDir: string;
  downloadDirPlaceholder: string;
  chooseDirectory: string;
  resetDefault: string;
  saving: string;
  saveSettings: string;
  settingsHintPath: string;
  settingsConfigPath: string;
  currentDir: string;
  systemDownloads: string;
};

export type SettingsViewProps = {
  labels: SettingsViewLabels;
  isSettingsLoading: boolean;
  locale: Locale;
  onLocaleChange: (locale: Locale) => void;
  batchSources: BatchSource[];
  onBatchSourceUrlChange: (index: number, url: string) => void;
  onBatchSourceJournalTitleChange: (index: number, journalTitle: string) => void;
  onAddBatchSource: () => void;
  onRemoveBatchSource: (index: number) => void;
  onMoveBatchSource: (index: number, direction: 'up' | 'down') => void;
  batchLimit: number;
  onBatchLimitChange: (value: string) => void;
  sameDomainOnly: boolean;
  onSameDomainOnlyChange: (checked: boolean) => void;
  pdfDownloadDir: string;
  onPdfDownloadDirChange: (value: string) => void;
  onChoosePdfDownloadDir: () => void;
  desktopRuntime: boolean;
  configPath: string;
  isSettingsSaving: boolean;
  onResetDownloadDir: () => void;
  onSaveSettings: () => void;
};
