import type { Locale } from '../language/i18n';
import type { SidebarArticle } from '../sidebar';

export type ReaderViewLabels = {
  untitled: string;
  unknown: string;
  authors: string;
  abstract: string;
  publishedAt: string;
  source: string;
  fetchedAt: string;
  emptyFiltered: string;
  emptyAll: string;
  startDate: string;
  endDate: string;
  journalFilterPlaceholder: string;
  fetchLatestBusy: string;
  fetchLatest: string;
  resetFilter: string;
  showing: string;
  total: string;
  emptyState: string;
  previewUnavailable: string;
};

export type ReaderViewProps = {
  isSidebarOpen: boolean;
  filteredArticles: SidebarArticle[];
  hasData: boolean;
  filterJournal: string;
  onFilterJournalChange: (value: string) => void;
  batchStartDate: string;
  onBatchStartDateChange: (value: string) => void;
  batchEndDate: string;
  onBatchEndDateChange: (value: string) => void;
  onFetchLatestBatch: () => void;
  isBatchLoading: boolean;
  onResetFilters: () => void;
  filteredCount: number;
  totalCount: number;
  browserUrl: string;
  previewCurrentUrl?: string;
  iframeReloadKey: number;
  electronRuntime: boolean;
  previewRuntime: boolean;
  labels: ReaderViewLabels;
};

export type SettingsViewLabels = {
  settingsTitle: string;
  settingsLoading: string;
  settingsLanguage: string;
  languageChinese: string;
  languageEnglish: string;
  settingsLanguageHint: string;
  settingsHomepageUrl: string;
  homepageUrlPlaceholder: string;
  settingsBatchOptions: string;
  batchCount: string;
  sameDomainOnly: string;
  settingsBatchHint: string;
  defaultPdfDir: string;
  downloadDirPlaceholder: string;
  chooseDirectory: string;
  resetDefault: string;
  saving: string;
  saveSettings: string;
  settingsHintPath: string;
  currentDir: string;
  systemDownloads: string;
};

export type SettingsViewProps = {
  labels: SettingsViewLabels;
  isSettingsLoading: boolean;
  locale: Locale;
  onLocaleChange: (locale: Locale) => void;
  homepageUrl: string;
  onHomepageUrlChange: (url: string) => void;
  batchLimit: number;
  onBatchLimitChange: (value: string) => void;
  sameDomainOnly: boolean;
  onSameDomainOnlyChange: (checked: boolean) => void;
  pdfDownloadDir: string;
  onPdfDownloadDirChange: (value: string) => void;
  onChoosePdfDownloadDir: () => void;
  desktopRuntime: boolean;
  isSettingsSaving: boolean;
  onResetDownloadDir: () => void;
  onSaveSettings: () => void;
};
