export * from 'ls/workbench/browser/editorModel';
export type { EditorDraftTabInput as WritingDraftEditorInput } from 'ls/workbench/browser/editorInput';
export type { EditorTabInput as WritingEditorInput } from 'ls/workbench/browser/editorInput';
export type { EditorTabViewMode as WritingEditorViewMode } from 'ls/workbench/browser/editorInput';
export type { EditorWorkspaceDraftTab as WritingWorkspaceDraftTab } from 'ls/workbench/browser/editorModel';
export type { EditorWorkspaceBrowserTab as WritingWorkspaceBrowserTab } from 'ls/workbench/browser/editorModel';
export type { EditorWorkspacePdfTab as WritingWorkspacePdfTab } from 'ls/workbench/browser/editorModel';
export type { EditorWorkspaceContentTab as WritingWorkspaceContentTab } from 'ls/workbench/browser/editorModel';
export type { EditorWorkspaceTab as WritingWorkspaceTab } from 'ls/workbench/browser/editorModel';
export type { EditorEditorGroupState as WritingEditorGroupState } from 'ls/workbench/browser/editorModel';
export type { EditorWorkspaceState as WritingWorkspaceState } from 'ls/workbench/browser/editorModel';
export type { EditorModelSnapshot as WritingEditorModelSnapshot } from 'ls/workbench/browser/editorModel';
export type { EditorGroupTarget as WritingEditorGroupTarget } from 'ls/workbench/browser/editorModel';
export { EditorModel as WritingEditorModel } from 'ls/workbench/browser/editorModel';
export { createEditorModel as createWritingEditorModel } from 'ls/workbench/browser/editorModel';
export { toEditorWorkspaceTabInput as toWritingWorkspaceTabInput } from 'ls/workbench/browser/editorModel';
